import Axios from 'axios'

const carriersApiBaseUrl = 'https://api.carriers.uat.glamit.com.ar/v1'
const glamitAuthToken = 'Bearer eyJraWQiOiJpZ25HTHdjbmlvU2xMQWtXRGhWZGExc25WcW9FTzJMNzBsOUY5R1pRSWp3PSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiUnJSZ2ZkYXJEQ1JRVTBhcWluR0dpUSIsInN1YiI6ImZkYWE5YWQxLWU1YjEtNDBmMC1iZDg1LTFjMGQ5NmRjNDViMSIsImNvZ25pdG86Z3JvdXBzIjpbIlJPTEVfR0xBTUlUX0FETUlOIiwidXMtZWFzdC0xX0szV0FQeFNGZV9Hb29nbGUiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX0szV0FQeFNGZSIsImNvZ25pdG86dXNlcm5hbWUiOiJnb29nbGVfMTEyMTY0MDk0NDgwMDIxMjY0NTcxIiwiZ2l2ZW5fbmFtZSI6Ikpvcm1hbiIsInBpY3R1cmUiOiJodHRwczpcL1wvbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbVwvYS1cL0FPaDE0R2hMUlkxd2xQaHFLTzlXaWg5emxqUDJqb3VsdUg1MFhkSnVuWmxyPXM5Ni1jIiwiYXVkIjoiMmVzaDBoNDFqbHF1OTI4ODViYWpyNjFpZnIiLCJpZGVudGl0aWVzIjpbeyJ1c2VySWQiOiIxMTIxNjQwOTQ0ODAwMjEyNjQ1NzEiLCJwcm92aWRlck5hbWUiOiJHb29nbGUiLCJwcm92aWRlclR5cGUiOiJHb29nbGUiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJ0cnVlIiwiZGF0ZUNyZWF0ZWQiOiIxNjAxOTE1NzE0MDE4In1dLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTYzNjAzOTI0NywibmFtZSI6Ikpvcm1hbiBFc3Bpbm96YSIsImV4cCI6MTYzOTQxNDMwMSwiaWF0IjoxNjM5MzI3OTAxLCJmYW1pbHlfbmFtZSI6IkVzcGlub3phIiwiZW1haWwiOiJqZXNwaW5vemFAZ2xhbWl0LmNvbS5hciJ9.shYmKw-BLkifIetovi8-pXZO1wyUOw5Nu4eZARMo1JefAHYeT6ViPlzg9XjZMdtIjBoPEMV7He1YCMyoC8FiH90Vz9SnnaoMoNk7dEFN9FT28HlvE_DFsycqJZOKsRpyUefQnfeV5s-yq2Rp_bz2ndEBFIGSOa-0C0J_zUDHOKukMFciHfkraem-kcGhY94PcHY9h71NTWVa0SGj61-kHpGS0fYRT9IQnDjeq77P5KCQvv1-Wo_B_VrhK-1QiMTqyEYfiAFQkRE1XSToDXhToPlShgsphF3ZT_UpWh7EOf6faApYB0eWDH3DJXeQDFRNkJ0StfFOejwyqOIuyPXLfw'
const axios = Axios.create({
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Authorization': glamitAuthToken,
    'Glamit-Env': ''
  },
  responseType: 'json'
})

export const getCarriers = () => {
  return axios.get(`${carriersApiBaseUrl}/carrier`)
}